#!/usr/bin/env bash
# ════════════════════════════════════════════════════════
#  Stegu Visualizer — Full stack: inference + API + frontend
#  - Auto setup (venv + npm) on first run
#  - Minimal .env + frontend/.env.local if missing (API proxy → full pipeline)
#  - Waits until :8001 and :8000 respond before starting Next.js
#
#  Run:  npm run dev   |   make dev   |   bash scripts/start-all.sh   |  run.command
# ════════════════════════════════════════════════════════
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_ROOT"

wait_for_http() {
  local url=$1
  local label=$2
  local max_attempts=${3:-60}
  local i=0
  while [ "$i" -lt "$max_attempts" ]; do
    if curl -sf --connect-timeout 1 --max-time 2 "$url" >/dev/null 2>&1; then
      echo "   ✓ $label"
      return 0
    fi
    sleep 0.5
    i=$((i + 1))
  done
  echo "   ⚠  $label — timeout (service may still be starting)"
  return 1
}

# ── Minimal root .env (API + inference URLs) ─────────────
if [ ! -f "$PROJECT_ROOT/.env" ]; then
  cat > "$PROJECT_ROOT/.env" << 'EOF'
# Stegu Visualizer — add GEMINI_API_KEY for AI image refinement
GEMINI_API_KEY=

INFERENCE_URL=http://localhost:8001
INFERENCE_BASE_URL=http://localhost:8001
API_BASE_URL=http://localhost:8000
NEXT_PUBLIC_API_URL=http://localhost:8000
API_PROXY_URL=http://localhost:8000

TEXTURES_DIR=./assets/textures/stegu
DATA_DIR=./data
MODEL_CACHE_DIR=./data/model-cache
EOF
  echo "→ Created minimal .env — set GEMINI_API_KEY if you use „Refine with AI”."
fi

# ── Frontend: proxy /api → FastAPI (required for full backend + inference) ─
if [ ! -f "$PROJECT_ROOT/frontend/.env.local" ]; then
  cat > "$PROJECT_ROOT/frontend/.env.local" << 'EOF'
# Auto-generated by scripts/start-all.sh — full stack (OneFormer + SAM2 + pipeline)
API_PROXY_URL=http://localhost:8000
NEXT_PUBLIC_API_URL=http://localhost:8000
EOF
  echo "→ Created frontend/.env.local with API_PROXY_URL (Next → FastAPI)."
fi

# ── Load environment ─────────────────────────────────────
set -a
# shellcheck disable=SC1091
source "$PROJECT_ROOT/.env"
set +a

# ── Resolve relative paths against project root ──────────
for _var in TEXTURES_DIR DATA_DIR MODEL_CACHE_DIR; do
  _val="${!_var:-}"
  if [ -n "$_val" ] && [[ "$_val" != /* ]]; then
    export "$_var"="$PROJECT_ROOT/$_val"
  fi
done

mkdir -p "$PROJECT_ROOT/data/uploads" \
         "$PROJECT_ROOT/data/outputs" \
         "$PROJECT_ROOT/data/masks" \
         "$PROJECT_ROOT/data/model-cache"

# ── Auto install: venvs + frontend deps ──────────────────
if [ ! -f "$PROJECT_ROOT/api/.venv/bin/uvicorn" ] \
   || [ ! -f "$PROJECT_ROOT/inference/.venv/bin/uvicorn" ] \
   || [ ! -d "$PROJECT_ROOT/frontend/node_modules" ]; then
  echo ""
  echo "→ First-time setup: venvs + pip + npm (make setup)…"
  make -C "$PROJECT_ROOT" setup
  echo ""
fi

echo ""
echo "═══ Stegu Visualizer — Full stack ═══"
echo ""

# ── 1) Inference (OneFormer + SAM2), port 8001 ────────────
echo "→ Starting inference   http://localhost:8001"
(cd "$PROJECT_ROOT/inference" \
  && "$PROJECT_ROOT/inference/.venv/bin/uvicorn" main:app \
     --host 0.0.0.0 --port 8001 \
     --log-level warning) &
echo $! > "$PROJECT_ROOT/.pid-inference"

echo "   …waiting for inference /health (models load in background)"
wait_for_http "http://127.0.0.1:8001/health" "inference service up (models loading in background)" 40 || true

# ── 2) API (pipeline + Gemini), port 8000 ────────────────
echo "→ Starting API         http://localhost:8000/api/health"
(cd "$PROJECT_ROOT/api" \
  && "$PROJECT_ROOT/api/.venv/bin/uvicorn" main:app \
     --host 0.0.0.0 --port 8000 \
     --log-level info) &
echo $! > "$PROJECT_ROOT/.pid-api"

echo "   …waiting for API /api/health"
wait_for_http "http://127.0.0.1:8000/api/health" "API ready" 80 || true

# ── 3) Frontend ─────────────────────────────────────────
echo "→ Starting frontend    http://localhost:3000"
(cd "$PROJECT_ROOT/frontend" && npm run dev 2>&1) &
echo $! > "$PROJECT_ROOT/.pid-frontend"

echo ""
echo "  ┌────────────────────────────────────────────────────────────┐"
echo "  │  Open:  http://localhost:3000                              │"
echo "  │  Stack: Next → API :8000 → Inference :8001 (OneFormer+SAM2) │"
echo "  │  Stop:  npm run stop   or   bash scripts/stop-all.sh       │"
echo "  └────────────────────────────────────────────────────────────┘"
echo ""

wait
